# **100. Regressão Linear com Redes Neurais artificiais parte 1**

Este projeto tem por objetivo desenvolver um algoritmo de Machine Learning para prever o valor do preço médio de casas em Boston. 

Os dados foram extraídos do site do Kaggle:

https://www.kaggle.com/schirmerchad/bostonhoustingmlnd

In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv(r'D:\Users\Nayan Couto\Cloud Drive\Documentos\Arquivos PDF, PPT, DOC\CURSOS\Machine Learning com Python\ML_Jupyter_Anaconda\Secao_6_RNA\Datasets\housing.csv',
                    sep=',', encoding='iso-8859-1')

In [30]:
df.head()

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

**Atributos previsores**

RM: é o número médio de cômodos entre os imóveis no bairro.

LSTAT: é a porcentagem de proprietários no bairro considerados de "classe baixa" (proletariado).

PTRATIO: é a razão entre estudantes e professores nas escolas de ensino fundamental e médio no bairro.

**Variável alvo**

MEDV: valor médio das casas

In [31]:
df.shape

(489, 4)

In [32]:
independente = df.iloc[:, 0:3].values
independente

array([[ 6.575,  4.98 , 15.3  ],
       [ 6.421,  9.14 , 17.8  ],
       [ 7.185,  4.03 , 17.8  ],
       ...,
       [ 6.976,  5.64 , 21.   ],
       [ 6.794,  6.48 , 21.   ],
       [ 6.03 ,  7.88 , 21.   ]])

In [33]:
independente.shape

(489, 3)

In [34]:
dependente = df.iloc[:, 3].values

In [35]:
dependente.shape

(489,)

## **TREINAMENTO**

In [36]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente, dependente, test_size = 0.3, random_state = 0)

In [37]:
x_treino.shape, x_teste.shape

((342, 3), (147, 3))

In [38]:
from sklearn.neural_network import MLPRegressor

In [99]:
redes = MLPRegressor(hidden_layer_sizes=(200, 200), activation='relu', verbose=True, max_iter=2000,
                    solver='lbfgs', random_state = 12)

In [100]:
redes.fit(x_treino, y_treino)

C:\Users\Nayan Couto\.conda\envs\POO\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPRegressor(hidden_layer_sizes=(200, 200), max_iter=2000, random_state=12,
             solver='lbfgs', verbose=True)

In [101]:
redes.n_layers_

4

In [102]:
redes.score(x_treino, y_treino)

0.8611555223495078

## **TESTE**

In [103]:
redes.score(x_teste, y_teste)

0.808920315601159

In [104]:
previsoes_teste = redes.predict(x_teste)

## **MÉTRICAS**

In [105]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [106]:
# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste)

56816.70326726268

In [108]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste))

74457.84444087482

### **Validação Cruzada**

In [109]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [110]:
# Separando os dados em folds
kfold = KFold(n_splits = 12, shuffle=True, random_state = 5)

In [111]:
# Criando o modelo
from sklearn.neural_network import MLPRegressor
modelo = MLPRegressor(hidden_layer_sizes=(200, 200), activation='relu', verbose=True, max_iter=2000,
                    solver='lbfgs', random_state = 12)
resultado = cross_val_score(modelo, independente, dependente, cv = kfold)
resultado

C:\Users\Nayan Couto\.conda\envs\POO\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\Nayan Couto\.conda\envs\POO\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\Nayan Couto\.conda\envs\POO\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converg

array([0.88358143, 0.87640335, 0.82605385, 0.79171526, 0.69660486,
       0.81701647, 0.69927824, 0.79936669, 0.75159404, 0.71544901,
       0.83151711, 0.67688294])

In [113]:
# Usamos a média e o desvio padrão
print("R²: %.2f%%" % (resultado.mean() * 100.0))

R²: 78.05%


## **RESULTADOS**

**REGRESSÃO LINEAR SIMPLES:** R^2 = 0,57/0,60; RMSE = 99315,5; R^2 Validação Cruzada: 55,97%

**REGRESSÃO LINEAR MÚLTIPLA:** R^2 = 0,73/0,68; RMSE = 96087,3; R^2 Validação Cruzada: 69,25%

**REGRESSÃO POLINOMIAL:** R^2 = 0,59/0,54; RMSE = 114670,6.

**REGRESSÃO SVR:** R^2 = 0,87/0,81; RMSE = 73422,7. R^2 Validação Cruzada: 82,37%.

**REGRESSÃO ÁRVORE DE DECISÃO:** R^2 = 0,91/0,83; RMSE = 71114,5. R^2 Validação Cruzada: 74,60%.

**REGRESSÃO COM RANDOM FOREST:** R^2 = 0,92/0,85; RMSE = 66729,3. R^2 Validação Cruzada: 82,85%.

**REGRESSÃO COM XGBOOST:** R^2 = 0,93/0,84; RMSE = 67788,8. R^2 Validação Cruzada: 83,22%.

**REGRESSÃO COM LIGHT GBM:** R^2 = 0,88/0,82; RMSE = 71906,4. R^2 Validação Cruzada: 82,38%.

**REGRESSÃO COM CATBOOST:** R^2 = 0,90/0,84; RMSE = 69053,3 R^2 Validação Cruzada: 83,40%.

**REGRESSÃO COM REDES NEURAIS:** R^2 = 0,86/0,81; RMSE = 74457,9. R^2 Validação Cruzada: 78,05%.

## **Padronização de escala**

In [114]:
from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
x_treino_scaler = x_scaler.fit_transform(x_treino)

In [115]:
x_treino_scaler

array([[ 0.05327517, -0.70150711, -0.05467118],
       [ 1.12799963, -0.44487061, -0.52922816],
       [ 0.60711128, -0.79792304,  0.230063  ],
       ...,
       [-0.33111532, -0.36121561, -0.33940537],
       [-0.31699486,  0.84398345, -0.29194967],
       [-0.33268427, -0.38815536, -0.90887374]])

In [116]:
y_scaler = StandardScaler()
y_treino_scaler = y_scaler.fit_transform(y_treino.reshape(-1,1))

In [117]:
y_treino_scaler

array([[-1.05925606e-02],
       [ 6.46900118e-01],
       [ 2.85923746e-01],
       [-1.13728667e-01],
       [ 1.44111599e-01],
       [-7.84113359e-01],
       [-1.24822584e+00],
       [-2.81324840e-01],
       [-1.39512694e-01],
       [-1.01616960e+00],
       [ 2.00056152e+00],
       [ 1.21414870e+00],
       [ 1.27860877e+00],
       [-1.52404707e-01],
       [ 9.04740384e-01],
       [ 2.29945267e-03],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [ 4.27735892e-01],
       [ 2.60139719e-01],
       [-1.06773765e+00],
       [-1.17087376e+00],
       [ 3.49603506e+00],
       [ 9.04740384e-01],
       [-2.07331469e+00],
       [ 1.69895626e-01],
       [ 4.27735892e-01],
       [ 2.76119030e+00],
       [-3.45784907e-01],
       [ 2.73031732e-01],
       [-1.48028208e+00],
       [ 1.57003612e-01],
       [-1.91080747e-01],
       [-1.01616960e+00],
       [ 3.37491799e-01],
       [-2.34845740e-02],
       [ 1.9

In [118]:
x_teste_scaler = x_scaler.transform(x_teste)
x_teste_scaler

array([[-6.24507256e-01, -6.20687880e-01,  1.17917695e+00],
       [ 9.56985082e-01, -8.43295235e-01, -2.61727885e+00],
       [-1.30072075e+00,  1.98112421e+00, -1.81053199e+00],
       [ 9.72674490e-01,  9.82935809e-01,  7.99531373e-01],
       [ 2.90185237e-01, -5.72479917e-01, -3.39405369e-01],
       [ 2.72926888e-01,  9.46070896e-01,  7.99531373e-01],
       [-2.08519115e+00,  2.33134087e+00, -1.81053199e+00],
       [-1.88341711e-01, -2.51777567e-02,  7.99531373e-01],
       [-1.08325729e-01, -2.13755962e-01, -2.44493974e-01],
       [-4.18976010e-01,  1.39296468e-01,  1.17917695e+00],
       [-1.41892805e-02,  1.26651206e+00,  7.99531373e-01],
       [-6.19800434e-01,  4.03022379e-01,  7.99531373e-01],
       [-2.99736508e-01, -7.29864736e-01,  5.14797187e-01],
       [-2.51664988e+00,  3.05162455e+00,  7.99531373e-01],
       [ 7.76556889e-01, -4.85989161e-01,  1.13172126e+00],
       [-7.45315699e-01,  6.32719141e-01,  1.27408835e+00],
       [ 7.36714050e-02, -1.24429444e-01

In [169]:
y_teste_scaler = y_scaler.transform(y_teste.reshape(-1,1))
y_teste_scaler

array([[-2.29756787e-01],
       [ 1.08522857e+00],
       [-1.06773765e+00],
       [ 7.50036225e-01],
       [ 1.18327572e-01],
       [-5.90733160e-01],
       [-1.27400987e+00],
       [ 1.18327572e-01],
       [-3.63765873e-02],
       [-2.68432827e-01],
       [-1.48028208e+00],
       [-1.48028208e+00],
       [-1.65296720e-01],
       [-4.87597053e-01],
       [ 7.50036225e-01],
       [-7.84113359e-01],
       [-2.16864774e-01],
       [ 2.08571666e-01],
       [ 9.25435458e-02],
       [ 1.13679662e+00],
       [ 1.20125669e+00],
       [ 1.44620494e+00],
       [-1.89282650e+00],
       [-8.79446405e-02],
       [-5.39165106e-01],
       [ 3.13505869e+00],
       [ 1.84585736e+00],
       [ 2.65805419e+00],
       [ 2.29945267e-03],
       [-6.21606139e-02],
       [-8.09897386e-01],
       [ 2.29945267e-03],
       [-1.52404707e-01],
       [ 2.52913406e+00],
       [-6.21606139e-02],
       [ 2.58070211e+00],
       [-2.42648800e-01],
       [-1.14508973e+00],
       [ 8.2

In [184]:
redes = MLPRegressor(hidden_layer_sizes=(6, 6), activation='relu', verbose=True, max_iter=1500,
                    solver='lbfgs', random_state = 12)

In [185]:
redes.fit(x_treino_scaler, y_treino_scaler.ravel())

MLPRegressor(hidden_layer_sizes=(6, 6), max_iter=1500, random_state=12,
             solver='lbfgs', verbose=True)

In [186]:
redes.n_layers_

4

In [187]:
redes.score(x_treino_scaler, y_treino_scaler)

0.8751927259348038

**TESTE**

In [188]:
redes.score(x_teste_scaler, y_teste_scaler)

0.8326836739133189

In [189]:
previsoes_teste_scaler = redes.predict(x_teste_scaler)

In [190]:
previsoes_teste_scaler

array([-2.68209691e-01,  1.30496964e+00, -7.31693840e-01, -1.05835046e+00,
        1.34347096e-01, -1.02192571e+00, -7.88556342e-01, -3.42984470e-01,
       -2.56884550e-02, -4.32905426e-01, -1.23508494e+00, -6.38283810e-01,
        3.46220591e-02, -1.52131673e+00,  6.01078366e-02, -5.74914843e-01,
        3.29722645e-02,  6.00434171e-01, -7.14615690e-02,  1.19809617e+00,
        1.53638419e+00,  1.62133798e+00, -1.54941520e+00,  5.29844031e-02,
       -3.00639477e-01,  2.56991002e+00,  1.95429772e+00,  2.53908623e+00,
       -3.16282435e-01, -2.63695440e-01, -9.59363133e-01, -4.03097081e-01,
        3.07951067e-03,  1.57331105e+00,  2.44170093e-02,  3.20850613e+00,
       -8.87398046e-02, -1.32591683e+00,  2.26736278e-01,  5.23140614e-01,
       -1.20926120e+00, -2.50978921e-01, -3.62754363e-01,  2.38944789e-01,
       -4.48972976e-01, -5.36216585e-01,  1.12887346e-01, -8.72685168e-01,
        2.96348448e+00, -2.98342074e-01,  1.59346214e+00,  4.86154395e-02,
        8.39781448e-01, -

## **MÉTRICAS**

**Revertendo a transformação**

In [191]:
previsoes_teste_scaler

array([-2.68209691e-01,  1.30496964e+00, -7.31693840e-01, -1.05835046e+00,
        1.34347096e-01, -1.02192571e+00, -7.88556342e-01, -3.42984470e-01,
       -2.56884550e-02, -4.32905426e-01, -1.23508494e+00, -6.38283810e-01,
        3.46220591e-02, -1.52131673e+00,  6.01078366e-02, -5.74914843e-01,
        3.29722645e-02,  6.00434171e-01, -7.14615690e-02,  1.19809617e+00,
        1.53638419e+00,  1.62133798e+00, -1.54941520e+00,  5.29844031e-02,
       -3.00639477e-01,  2.56991002e+00,  1.95429772e+00,  2.53908623e+00,
       -3.16282435e-01, -2.63695440e-01, -9.59363133e-01, -4.03097081e-01,
        3.07951067e-03,  1.57331105e+00,  2.44170093e-02,  3.20850613e+00,
       -8.87398046e-02, -1.32591683e+00,  2.26736278e-01,  5.23140614e-01,
       -1.20926120e+00, -2.50978921e-01, -3.62754363e-01,  2.38944789e-01,
       -4.48972976e-01, -5.36216585e-01,  1.12887346e-01, -8.72685168e-01,
        2.96348448e+00, -2.98342074e-01,  1.59346214e+00,  4.86154395e-02,
        8.39781448e-01, -

In [192]:
previsoes_teste_inverse = y_scaler.inverse_transform(previsoes_teste_scaler.reshape(-1,1))

In [193]:
previsoes_teste_inverse

array([[411636.34699899],
       [667893.96203783],
       [336138.6966176 ],
       [282929.0941388 ],
       [477209.44495801],
       [288862.37890029],
       [326876.27572069],
       [399456.1674807 ],
       [451141.0064076 ],
       [384808.80380529],
       [254140.54072583],
       [351354.40095154],
       [460965.07938501],
       [207515.80195697],
       [465116.4971285 ],
       [361676.67005708],
       [460696.34179103],
       [553131.09002221],
       [443684.95302381],
       [650485.17760309],
       [705589.43622052],
       [719427.6907198 ],
       [202938.79810893],
       [463956.15002249],
       [406353.80886773],
       [873942.05939713],
       [773664.01824513],
       [868921.12449911],
       [403805.7033159 ],
       [412371.68020345],
       [299053.29314578],
       [389664.33128492],
       [455827.06485581],
       [711604.51096163],
       [459302.76303518],
       [977963.96721926],
       [440870.47449831],
       [239344.79368444],
       [4922

In [194]:
y_teste

array([ 417900.,  632100.,  281400.,  577500.,  474600.,  359100.,
        247800.,  474600.,  449400.,  411600.,  214200.,  214200.,
        428400.,  375900.,  577500.,  327600.,  420000.,  489300.,
        470400.,  640500.,  651000.,  690900.,  147000.,  441000.,
        367500.,  966000.,  756000.,  888300.,  455700.,  445200.,
        323400.,  455700.,  430500.,  867300.,  445200.,  875700.,
        415800.,  268800.,  590100.,  497700.,  231000.,  315000.,
        388500.,  449400.,  413700.,  352800.,  453600.,  306600.,
        898800.,  514500.,  743400.,  474600.,  600600.,  304500.,
        661500.,  489300.,  422100.,  184800.,  525000.,  249900.,
        407400.,  361200.,  428400.,  392700.,  428400.,  472500.,
        258300.,  550200.,  346500.,  199500.,  302400.,  611100.,
        396900.,  585900.,  279300.,  483000.,  462000.,  218400.,
        518700.,  420000.,  392700.,  980700.,  455700.,  514500.,
        480900.,  520800.,  485100.,  525000.,  390600.,  5691

In [195]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [196]:
# Erro médio Absoluto
mean_absolute_error(y_teste, previsoes_teste_inverse)

51925.51007283016

In [197]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_teste, previsoes_teste_inverse))

69674.25946129963

**Revertendo a transformação**

In [198]:
x_treino_inverse = x_scaler.inverse_transform(x_treino_scaler)

In [199]:
x_treino_inverse

array([[ 6.266,  7.9  , 18.4  ],
       [ 6.951,  9.71 , 17.4  ],
       [ 6.619,  7.22 , 19.   ],
       ...,
       [ 6.021, 10.3  , 17.8  ],
       [ 6.03 , 18.8  , 17.9  ],
       [ 6.02 , 10.11 , 16.6  ]])

In [200]:
x_treino

array([[ 6.266,  7.9  , 18.4  ],
       [ 6.951,  9.71 , 17.4  ],
       [ 6.619,  7.22 , 19.   ],
       ...,
       [ 6.021, 10.3  , 17.8  ],
       [ 6.03 , 18.8  , 17.9  ],
       [ 6.02 , 10.11 , 16.6  ]])

In [201]:
y_treino_inverse = y_scaler.inverse_transform(y_treino_scaler)

In [202]:
y_treino_inverse

array([[ 453600.],
       [ 560700.],
       [ 501900.],
       [ 436800.],
       [ 478800.],
       [ 327600.],
       [ 252000.],
       [ 409500.],
       [ 432600.],
       [ 289800.],
       [ 781200.],
       [ 653100.],
       [ 663600.],
       [ 430500.],
       [ 602700.],
       [ 455700.],
       [ 409500.],
       [ 499800.],
       [ 409500.],
       [ 499800.],
       [ 525000.],
       [ 497700.],
       [ 281400.],
       [ 264600.],
       [1024800.],
       [ 602700.],
       [ 117600.],
       [ 483000.],
       [ 525000.],
       [ 905100.],
       [ 399000.],
       [ 499800.],
       [ 214200.],
       [ 480900.],
       [ 424200.],
       [ 289800.],
       [ 510300.],
       [ 451500.],
       [ 766500.],
       [ 510300.],
       [ 369600.],
       [ 466200.],
       [ 312900.],
       [ 407400.],
       [ 273000.],
       [ 392700.],
       [ 294000.],
       [ 556500.],
       [ 178500.],
       [ 728700.],
       [ 157500.],
       [ 367500.],
       [ 327

In [203]:
x_teste_inverse = x_scaler.inverse_transform(x_teste_scaler)

In [204]:
x_teste_inverse

array([[ 5.834,  8.47 , 21.   ],
       [ 6.842,  6.9  , 13.   ],
       [ 5.403, 26.82 , 14.7  ],
       [ 6.852, 19.78 , 20.2  ],
       [ 6.417,  8.81 , 17.8  ],
       [ 6.406, 19.52 , 20.2  ],
       [ 4.903, 29.29 , 14.7  ],
       [ 6.112, 12.67 , 20.2  ],
       [ 6.163, 11.34 , 18.   ],
       [ 5.965, 13.83 , 21.   ],
       [ 6.223, 21.78 , 20.2  ],
       [ 5.837, 15.69 , 20.2  ],
       [ 6.041,  7.7  , 19.6  ],
       [ 4.628, 34.37 , 20.2  ],
       [ 6.727,  9.42 , 20.9  ],
       [ 5.757, 17.31 , 21.2  ],
       [ 6.279, 11.97 , 18.7  ],
       [ 6.51 ,  7.39 , 14.7  ],
       [ 5.807, 16.03 , 18.6  ],
       [ 6.739,  4.69 , 15.2  ],
       [ 7.327, 11.25 , 13.   ],
       [ 7.135,  4.45 , 17.   ],
       [ 4.519, 36.98 , 20.2  ],
       [ 5.85 ,  8.77 , 19.2  ],
       [ 5.569, 15.1  , 19.2  ],
       [ 7.645,  3.01 , 14.9  ],
       [ 7.333,  7.79 , 13.   ],
       [ 7.61 ,  3.11 , 14.7  ],
       [ 6.395, 13.27 , 20.2  ],
       [ 6.019, 12.92 , 19.2  ],
       [ 6

In [205]:
y_teste_inverse = y_scaler.inverse_transform(y_teste_scaler)

In [206]:
y_teste_inverse

array([[ 417900.],
       [ 632100.],
       [ 281400.],
       [ 577500.],
       [ 474600.],
       [ 359100.],
       [ 247800.],
       [ 474600.],
       [ 449400.],
       [ 411600.],
       [ 214200.],
       [ 214200.],
       [ 428400.],
       [ 375900.],
       [ 577500.],
       [ 327600.],
       [ 420000.],
       [ 489300.],
       [ 470400.],
       [ 640500.],
       [ 651000.],
       [ 690900.],
       [ 147000.],
       [ 441000.],
       [ 367500.],
       [ 966000.],
       [ 756000.],
       [ 888300.],
       [ 455700.],
       [ 445200.],
       [ 323400.],
       [ 455700.],
       [ 430500.],
       [ 867300.],
       [ 445200.],
       [ 875700.],
       [ 415800.],
       [ 268800.],
       [ 590100.],
       [ 497700.],
       [ 231000.],
       [ 315000.],
       [ 388500.],
       [ 449400.],
       [ 413700.],
       [ 352800.],
       [ 453600.],
       [ 306600.],
       [ 898800.],
       [ 514500.],
       [ 743400.],
       [ 474600.],
       [ 600

In [207]:
y_teste

array([ 417900.,  632100.,  281400.,  577500.,  474600.,  359100.,
        247800.,  474600.,  449400.,  411600.,  214200.,  214200.,
        428400.,  375900.,  577500.,  327600.,  420000.,  489300.,
        470400.,  640500.,  651000.,  690900.,  147000.,  441000.,
        367500.,  966000.,  756000.,  888300.,  455700.,  445200.,
        323400.,  455700.,  430500.,  867300.,  445200.,  875700.,
        415800.,  268800.,  590100.,  497700.,  231000.,  315000.,
        388500.,  449400.,  413700.,  352800.,  453600.,  306600.,
        898800.,  514500.,  743400.,  474600.,  600600.,  304500.,
        661500.,  489300.,  422100.,  184800.,  525000.,  249900.,
        407400.,  361200.,  428400.,  392700.,  428400.,  472500.,
        258300.,  550200.,  346500.,  199500.,  302400.,  611100.,
        396900.,  585900.,  279300.,  483000.,  462000.,  218400.,
        518700.,  420000.,  392700.,  980700.,  455700.,  514500.,
        480900.,  520800.,  485100.,  525000.,  390600.,  5691

# **DESAFIO 4**

DESENVOLVER UM ALGORITMO DE REDES NEURAIS ARTFICIAIS DE REGRESSÃO PARA DATASET DO LINK A SEGUIR:

https://www.kaggle.com/mirichoi0218/insurance/code